In [1]:
import numpy as np

In [10]:
# 1
a, b = np.array([1.0]), np.array([4.0])
print(np.add(a, b)[0])
print(np.subtract(a, b)[0])
print(np.multiply(a, b)[0])
print(np.divide(a, b)[0])

5.0
-3.0
4.0
0.25


In [11]:
# 2
arr = np.array([-120, -130, -140])
log_sum_exp = np.log(np.sum(np.exp(arr)))
log_sum_exp_base2 = np.log2(np.sum(np.exp2(arr)))
print(log_sum_exp)
print(log_sum_exp_base2)

-119.99995459903973
-119.99859043108894


In [13]:
# 3
print(np.arange(10)/ 3)

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [14]:
# 4.
array_4 = np.array([1.0, 2.0, 3.0, 4.0])
floor_div_result = np.floor_divide(array_4, 1.5)
print(array_4)
print(floor_div_result)

[1. 2. 3. 4.]
[0. 1. 2. 2.]


In [16]:
# 5
array_5 = np.array([0, 1, 2, 3, 4, 5, 6])
power_result = np.power(array_5, array_5)
print(array_5)
print(power_result)

[0 1 2 3 4 5 6]
[    1     1     4    27   256  3125 46656]


In [17]:
# 6
array_6 = np.array([0, 1, 2, 3, 4, 5, 6])
remainder_result = np.remainder(array_6, 5)
print(array_6)
print(remainder_result)

[0 1 2 3 4 5 6]
[0 1 2 3 4 0 1]


In [18]:
# 7
print(np.abs(np.array([-10.2, 122.2, 0.2])))

[ 10.2 122.2   0.2]


In [19]:
# 8
array_1 = np.array([1.111, 2.222, 2.333])
array_2 = np.array([0.333, 0.555, 0.666])
array_3 = np.array([0.111, 2.222, 2.444, 4.444, 4.555])
print(np.round(array_1, 1))
print(np.round(array_2, 1))
print(np.round(array_3, 0))

[1.1 2.2 2.3]
[0.3 0.6 0.7]
[0. 2. 2. 4. 5.]
